'use strict';

// ============================================================
// AREAS
// ============================================================
const AREAS = [
  {
    id: 'neighborhood',
    defaultLandmark: 'konbini',
    name: '近所',
    emoji: '🏘️',
    phase: 'japan',
    requiredVehicle: null,
    baseMoney: 250,
    baseFollowers: 8,
    basePop: 1,
    spots: [
      { id: 'nb_01', name: 'コンビニ',             emoji: '🏪', desc: '深夜も明かりが灯る' },
      { id: 'nb_02', name: '近所の公園',           emoji: '🌳', desc: 'ベンチで一休み' },
      { id: 'nb_03', name: '地元神社',             emoji: '⛩️', desc: '古くから続く氏神様' },
      { id: 'nb_04', name: 'バス停',               emoji: '🚌', desc: '時刻表を眺める朝' },
      { id: 'nb_05', name: 'スーパー',             emoji: '🛒', desc: '夕方は特売で賑わう' },
      { id: 'nb_06', name: 'ドラッグストア',       emoji: '💊', desc: '日用品なんでも揃う' },
      { id: 'nb_07', name: '本屋',                 emoji: '📚', desc: '立ち読みの聖地' },
      { id: 'nb_08', name: '郵便局',               emoji: '📮', desc: '赤いポストが目印' },
      { id: 'nb_09', name: '角カフェ',             emoji: '☕', desc: 'モーニングセット人気' },
      { id: 'nb_10', name: '商店街',               emoji: '🏬', desc: 'レトロアーケード街' },
      { id: 'nb_11', name: '猫の路地',             emoji: '🐱', desc: '猫が集まる秘密の場所' },
      { id: 'nb_12', name: '川沿い遊歩道',         emoji: '🌊', desc: '散歩コースの定番' },
      { id: 'nb_13', name: '夕日の橋',             emoji: '🌉', desc: '黄金色に輝く夕暮れ' },
      { id: 'nb_14', name: '桜の公園',             emoji: '🌸', desc: '春には満開の花見' },
      { id: 'nb_15', name: '自転車屋',             emoji: '🔧', desc: 'パンク修理もお任せ' },
      { id: 'nb_16', name: 'コインランドリー',     emoji: '🌀', desc: '待ち時間に読書タイム' },
      { id: 'nb_17', name: '交差点',               emoji: '🚦', desc: '人が行き交う要所' },
      { id: 'nb_18', name: '学校前',               emoji: '🏫', desc: '下校の声が賑やか' },
      { id: 'nb_19', name: 'バッティングセンター', emoji: '⚾', desc: 'ストレス発散の場所' },
      { id: 'nb_20', name: '居酒屋横丁',           emoji: '🍻', desc: '夜は常連客で満員' },
      { id: 'nb_21', name: '豆腐屋',               emoji: '🤍', desc: '早朝から豆乳の香り' },
      { id: 'nb_22', name: '花屋',                 emoji: '💐', desc: '季節の花が並ぶ店' },
      { id: 'nb_23', name: '地元ラーメン屋',       emoji: '🍜', desc: '行列のできる名店' },
      { id: 'nb_24', name: '理容店',               emoji: '💈', desc: 'ゆっくり髪を整える' },
      { id: 'nb_25', name: 'お寺',                 emoji: '🛕', desc: '静かな境内で瞑想' },
      { id: 'nb_26', name: '公園のベンチ',         emoji: '🪑', desc: 'のんびりと空を眺める' },
      { id: 'nb_27', name: '空き地',               emoji: '🌱', desc: '雑草が生い茂る原っぱ' },
      { id: 'nb_28', name: 'ガスステーション',     emoji: '⛽', desc: '深夜も煌々と光る' },
      { id: 'nb_29', name: 'ファストフード',       emoji: '🍔', desc: '100円コーヒーが好評' },
      { id: 'nb_30', name: '写真館',               emoji: '📷', desc: '証明写真から記念写真まで' },
      { id: 'nb_31', name: '交番',                 emoji: '👮', desc: '安心の街の見守り番' },
      { id: 'nb_32', name: '路地アート',           emoji: '🎨', desc: '壁に描かれた謎の絵' },
      { id: 'nb_33', name: '公園噴水',             emoji: '⛲', desc: '夏は子供の水遊び場' },
      { id: 'nb_34', name: '八百屋',               emoji: '🥦', desc: 'おじいさんの威勢が良い' },
      { id: 'nb_35', name: '武道館',               emoji: '🥋', desc: '地元の子が稽古に励む' },
      { id: 'nb_36', name: '雪の街角',             emoji: '❄️', desc: '静かに雪が積もる朝' },
      { id: 'nb_37', name: '朝霧の川',             emoji: '🌫️', desc: '幻想的な霧景色' },
      { id: 'nb_38', name: '和菓子屋',             emoji: '🍡', desc: 'おはぎと大福が人気' },
      { id: 'nb_39', name: '古民家',               emoji: '🏚️', desc: '昭和レトロな空気感' },
      { id: 'nb_40', name: '屋台',                 emoji: '🍢', desc: 'おでんとたこ焼きあり' },
      { id: 'nb_41', name: 'コインパーキング',     emoji: '🅿️', desc: '路上駐車禁止の見張り' },
      { id: 'nb_42', name: '運動公園',             emoji: '🏃', desc: 'ジョギングの朝が爽快' },
      { id: 'nb_43', name: '夜の神社',             emoji: '🌙', desc: '提灯が揺れる静寂' },
      { id: 'nb_44', name: '焼き鳥屋',             emoji: '🍡', desc: '炭火の煙が食欲をそそる' },
      { id: 'nb_45', name: '地域センター',         emoji: '🏢', desc: 'サークル活動の拠点' },
      { id: 'nb_46', name: 'プール',               emoji: '🏊', desc: '夏は子供たちの天国' },
      { id: 'nb_47', name: '幼稚園前',             emoji: '🧒', desc: '送迎の自転車が並ぶ' },
      { id: 'nb_48', name: '川の鯉のぼり',         emoji: '🎏', desc: '端午の節句に揺れる' },
      { id: 'nb_49', name: '夕焼けの展望台',       emoji: '🌅', desc: '街が茜色に染まる頃' },
      { id: 'nb_50', name: 'お祭り広場',           emoji: '🏮', desc: '夏は盆踊りで盛り上がる' },
    ],
  },

  {
    id: 'city',
    defaultLandmark: 'station',
    name: '市内',
    emoji: '🏙️',
    phase: 'japan',
    requiredVehicle: 'bicycle',
    baseMoney: 1500,
    baseFollowers: 45,
    basePop: 5,
    spots: [
      { id: 'ci_01', name: '市役所前',             emoji: '🏛️', desc: '市民の声が集まる場所' },
      { id: 'ci_02', name: '図書館',               emoji: '📖', desc: '静寂の中の知の宝庫' },
      { id: 'ci_03', name: '城址公園',             emoji: '🏯', desc: '歴史を感じる石垣' },
      { id: 'ci_04', name: '地元グルメ街',         emoji: '🍱', desc: 'ご当地メニューが勢揃い' },
      { id: 'ci_05', name: '大型ショッピングモール', emoji: '🛍️', desc: '全フロア制覇に挑戦' },
      { id: 'ci_06', name: '祭り会場',             emoji: '🏮', desc: '年に一度の大イベント' },
      { id: 'ci_07', name: '博物館',               emoji: '🏛️', desc: '地域の歴史が凝縮' },
      { id: 'ci_08', name: '動物園',               emoji: '🦁', desc: 'パンダに長蛇の列' },
      { id: 'ci_09', name: '植物園',               emoji: '🌺', desc: '四季折々の花が咲く' },
      { id: 'ci_10', name: '遊園地',               emoji: '🎡', desc: '子供から大人まで楽しむ' },
      { id: 'ci_11', name: '水族館',               emoji: '🐠', desc: 'クラゲの幻想的な泳ぎ' },
      { id: 'ci_12', name: '中央駅',               emoji: '🚉', desc: '街の玄関口' },
      { id: 'ci_13', name: '商業ビル屋上',         emoji: '🏢', desc: '街を一望する絶景' },
      { id: 'ci_14', name: '美術館',               emoji: '🖼️', desc: '地元アーティストの展示' },
      { id: 'ci_15', name: '競技場',               emoji: '🏟️', desc: 'スポーツ観戦で熱狂' },
      { id: 'ci_16', name: '地元球場',             emoji: '⚾', desc: '応援の声が響き渡る' },
      { id: 'ci_17', name: '市民プール',           emoji: '🏊', desc: '夏の混雑がすごい' },
      { id: 'ci_18', name: 'バスターミナル',       emoji: '🚌', desc: '各地へ続く出発点' },
      { id: 'ci_19', name: '大型書店',             emoji: '📚', desc: '何時間でもいられる' },
      { id: 'ci_20', name: '映画館',               emoji: '🎬', desc: '大スクリーンで没入体験' },
      { id: 'ci_21', name: 'ゲームセンター',       emoji: '🕹️', desc: 'UFOキャッチャーに熱中' },
      { id: 'ci_22', name: '百貨店',               emoji: '🏬', desc: '地下食品街は絶品' },
      { id: 'ci_23', name: '市場',                 emoji: '🐟', desc: '新鮮な食材が並ぶ朝' },
      { id: 'ci_24', name: '公民館',               emoji: '🏠', desc: '地域の集会所' },
      { id: 'ci_25', name: '公立病院',             emoji: '🏥', desc: '白衣の先生が行き交う' },
      { id: 'ci_26', name: '大学キャンパス',       emoji: '🎓', desc: '若者のエネルギーが溢れる' },
      { id: 'ci_27', name: '科学館',               emoji: '🔭', desc: 'プラネタリウムが人気' },
      { id: 'ci_28', name: '郷土資料館',           emoji: '📜', desc: '地域の民具が展示' },
      { id: 'ci_29', name: '中心街アーケード',     emoji: '🏪', desc: '昭和の面影が残る商店街' },
      { id: 'ci_30', name: 'フードコート',         emoji: '🍣', desc: 'バラエティ豊かなグルメ' },
      { id: 'ci_31', name: '公園の池',             emoji: '🦢', desc: '白鳥が優雅に泳ぐ' },
      { id: 'ci_32', name: 'ホテルロビー',         emoji: '🏨', desc: '洗練された空間' },
      { id: 'ci_33', name: '観光案内所',           emoji: '🗺️', desc: '地元情報を仕入れる' },
      { id: 'ci_34', name: 'レトロ喫茶',           emoji: '☕', desc: 'ナポリタンとプリン' },
      { id: 'ci_35', name: 'スポーツジム',         emoji: '💪', desc: '夜遅くまで汗を流す' },
      { id: 'ci_36', name: '手作り市',             emoji: '🎪', desc: '週末だけの特別マーケット' },
      { id: 'ci_37', name: 'カラオケ店',           emoji: '🎤', desc: '防音ルームで熱唱' },
      { id: 'ci_38', name: 'ボウリング場',         emoji: '🎳', desc: 'ストライクで盛り上がる' },
      { id: 'ci_39', name: 'ネットカフェ',         emoji: '💻', desc: '漫画も読み放題' },
      { id: 'ci_40', name: '銭湯',                 emoji: '♨️', desc: '富士山の壁絵が定番' },
      { id: 'ci_41', name: '老舗和食店',           emoji: '🍱', desc: '三代続く味の継承' },
      { id: 'ci_42', name: '市立体育館',           emoji: '🏸', desc: '市民大会の舞台' },
      { id: 'ci_43', name: 'ラーメン横丁',         emoji: '🍜', desc: '各店が個性を競う路地' },
      { id: 'ci_44', name: '夜の繁華街',           emoji: '🌃', desc: 'ネオンが輝く夜の街' },
      { id: 'ci_45', name: '朝市',                 emoji: '🌄', desc: '早起きした人だけの特権' },
      { id: 'ci_46', name: '古書店街',             emoji: '📕', desc: '掘り出し物を探す旅' },
      { id: 'ci_47', name: '市民農園',             emoji: '🌽', desc: '野菜作りに挑む市民' },
      { id: 'ci_48', name: '夜のイルミネーション', emoji: '✨', desc: '冬の定番デートスポット' },
      { id: 'ci_49', name: '港の夕景',             emoji: '🌅', desc: '漁船が帰る夕暮れ時' },
      { id: 'ci_50', name: '山の展望台',           emoji: '⛰️', desc: '街を見渡す絶景ポイント' },
      { id: 'ci_51', name: '地元のお城',           emoji: '🏯', desc: '天守閣から見る市内' },
      { id: 'ci_52', name: '河川敷広場',           emoji: '🌿', desc: 'バーベキュー禁止の張り紙' },
      { id: 'ci_53', name: 'フリマ会場',           emoji: '🛒', desc: '掘り出し物の宝庫' },
      { id: 'ci_54', name: '地元花火大会',         emoji: '🎆', desc: '夏の夜空を彩る大輪' },
      { id: 'ci_55', name: '市の文化ホール',       emoji: '🎭', desc: 'コンサートや演劇の舞台' },
    ],
  },

  {
    id: 'downtown',
    defaultLandmark: 'tokyo_tower',
    name: '都内',
    emoji: '🗼',
    phase: 'japan',
    requiredVehicle: 'ekickboard',
    baseMoney: 8000,
    baseFollowers: 200,
    basePop: 20,
    spots: [
      { id: 'dt_01', name: '渋谷スクランブル',         emoji: '🚶', desc: '世界最多の交差点',         landmark: 'shibuya' },
      { id: 'dt_02', name: '原宿竹下通り',             emoji: '🎀', desc: '原宿スイーツの聖地',       landmark: 'harajuku' },
      { id: 'dt_03', name: '表参道',                   emoji: '🛍️', desc: 'ラグジュアリーブランド街' },
      { id: 'dt_04', name: '六本木ヒルズ',             emoji: '🌆', desc: '夜景が輝く都市の頂点' },
      { id: 'dt_05', name: '東京タワー',               emoji: '🗼', desc: '赤と白のシンボル',         landmark: 'tokyo_tower' },
      { id: 'dt_06', name: '銀座',                     emoji: '💎', desc: '日本一の高級ショッピング街' },
      { id: 'dt_07', name: '築地場外市場',             emoji: '🐟', desc: '新鮮な海鮮丼に舌鼓',       landmark: 'tsukiji' },
      { id: 'dt_08', name: 'お台場',                   emoji: '🗽', desc: '湾岸エンタメエリア',       landmark: 'odaiba' },
      { id: 'dt_09', name: '浅草寺',                   emoji: '⛩️', desc: '雷門をくぐって参拝',       landmark: 'asakusa' },
      { id: 'dt_10', name: '上野公園',                 emoji: '🌸', desc: '花見の聖地、博物館の街',   landmark: 'ueno' },
      { id: 'dt_11', name: '秋葉原',                   emoji: '🤖', desc: '電気街とアニメの聖地',     landmark: 'akihabara' },
      { id: 'dt_12', name: '新宿歌舞伎町',             emoji: '🌃', desc: 'ネオンが輝く眠らない街' },
      { id: 'dt_13', name: '池袋サンシャイン',         emoji: '🏢', desc: 'サンシャイン60が圧巻' },
      { id: 'dt_14', name: '下北沢',                   emoji: '🎸', desc: 'サブカルと古着の聖地' },
      { id: 'dt_15', name: '中目黒',                   emoji: '🌊', desc: '目黒川の桜並木が最高' },
      { id: 'dt_16', name: '吉祥寺',                   emoji: '🎪', desc: '住みたい街No.1の魅力' },
      { id: 'dt_17', name: '東京スカイツリー',         emoji: '🗺️', desc: '世界一の高さを誇る電波塔', landmark: 'skytree' },
      { id: 'dt_18', name: '代々木公園',               emoji: '🌳', desc: '都会のオアシス' },
      { id: 'dt_19', name: '新宿御苑',                 emoji: '🌿', desc: '都内最大の庭園' },
      { id: 'dt_20', name: '東京国立博物館',           emoji: '🏛️', desc: '日本最大の博物館' },
      { id: 'dt_21', name: 'お台場大観覧車',           emoji: '🎡', desc: '湾岸をぐるりと一望' },
      { id: 'dt_22', name: '豊洲市場',                 emoji: '🐠', desc: 'まぐろの競りは圧巻' },
      { id: 'dt_23', name: '渋谷ヒカリエ',             emoji: '✨', desc: '渋谷を見下ろす展望フロア' },
      { id: 'dt_24', name: '六本木アートナイト',       emoji: '🎨', desc: '夜の芸術の祭典' },
      { id: 'dt_25', name: '丸の内ビジネス街',         emoji: '💼', desc: '東京の経済を支える一帯' },
      { id: 'dt_26', name: '皇居前広場',               emoji: '🏰', desc: '緑と歴史が共存する空間' },
      { id: 'dt_27', name: '東京駅',                   emoji: '🚄', desc: '赤レンガの格調高い駅舎' },
      { id: 'dt_28', name: '神田神保町',               emoji: '📚', desc: '世界最大の古書店街' },
      { id: 'dt_29', name: '谷根千',                   emoji: '🏘️', desc: '下町情緒たっぷりの路地' },
      { id: 'dt_30', name: '自由が丘',                 emoji: '🍰', desc: 'スイーツの街でお洒落散歩' },
      { id: 'dt_31', name: '二子玉川',                 emoji: '🌊', desc: '多摩川沿いのオシャレタウン' },
      { id: 'dt_32', name: '恵比寿ガーデンプレイス', emoji: '🍷', desc: 'おしゃれな複合施設' },
      { id: 'dt_33', name: '青山墓地',                 emoji: '🌸', desc: '桜並木で有名な都会の緑地' },
      { id: 'dt_34', name: '品川水族館',               emoji: '🐋', desc: '都内で海の生き物に出会う' },
      { id: 'dt_35', name: '高円寺',                   emoji: '👘', desc: '阿波踊りと古着の街' },
      { id: 'dt_36', name: '三鷹の森ジブリ美術館',   emoji: '🌿', desc: '宮崎ワールドに浸る' },
      { id: 'dt_37', name: '立川昭和記念公園',         emoji: '🌺', desc: '四季の花が壮大に広がる' },
      { id: 'dt_38', name: '府中大國魂神社',           emoji: '⛩️', desc: '武蔵の国の総社' },
      { id: 'dt_39', name: '深川江戸資料館',           emoji: '🏮', desc: '江戸の街並みを再現' },
      { id: 'dt_40', name: '葛西臨海公園',             emoji: '🦀', desc: '東京湾に面した大公園' },
      { id: 'dt_41', name: '東京ドーム',               emoji: '⚾', desc: '巨人戦の熱気が凄まじい' },
      { id: 'dt_42', name: '神楽坂',                   emoji: '🍶', desc: 'フランス人も住む和の空間' },
      { id: 'dt_43', name: '蔵前',                     emoji: '🎁', desc: 'クラフト系ショップが集結' },
      { id: 'dt_44', name: '月島もんじゃ街',           emoji: '🥞', desc: 'もんじゃ焼きの発祥の地' },
      { id: 'dt_45', name: '等々力渓谷',               emoji: '🌿', desc: '23区唯一の渓谷' },
      { id: 'dt_46', name: '駒沢オリンピック公園',     emoji: '🏅', desc: '1964年東京五輪の遺産' },
      { id: 'dt_47', name: '砧公園',                   emoji: '🌳', desc: '世田谷区民の憩いの場' },
      { id: 'dt_48', name: '新橋サラリーマン街',       emoji: '🍺', desc: '昭和な居酒屋が並ぶ' },
      { id: 'dt_49', name: '芝大門増上寺',             emoji: '🛕', desc: '東京タワーと共に映える' },
      { id: 'dt_50', name: '赤坂TBS',                 emoji: '📺', desc: 'アイドルに会えるかも？' },
      { id: 'dt_51', name: '表参道ヒルズ',             emoji: '🏛️', desc: '安藤忠雄設計の芸術建築' },
      { id: 'dt_52', name: '明治神宮',                 emoji: '⛩️', desc: '都会の森に囲まれた神域' },
      { id: 'dt_53', name: '渋谷109',                 emoji: '🛍️', desc: '若者ファッションの発信地' },
      { id: 'dt_54', name: '上野アメ横',               emoji: '🛒', desc: '年末の混雑が名物' },
      { id: 'dt_55', name: '浜離宮恩賜庭園',           emoji: '🌊', desc: '海水を引き込む大名庭園' },
    ],
  },

  {
    id: 'kanto',
    defaultLandmark: 'kamakura',
    name: '関東',
    emoji: '🗾',
    phase: 'japan',
    requiredVehicle: 'moped',
    baseMoney: 45000,
    baseFollowers: 1000,
    basePop: 80,
    spots: [
      { id: 'ka_01', name: '川越小江戸',               emoji: '🏯', desc: '蔵造りの町並みが続く',       landmark: 'kawagoe' },
      { id: 'ka_02', name: '横浜中華街',               emoji: '🥟', desc: '本格中国料理が軒を並べる' },
      { id: 'ka_03', name: 'みなとみらい',             emoji: '⚓', desc: '横浜の近未来的な港街' },
      { id: 'ka_04', name: '赤レンガ倉庫',             emoji: '🏚️', desc: '明治の歴史が残る港の倉庫', landmark: 'yokohama_red' },
      { id: 'ka_05', name: '鎌倉大仏',                 emoji: '🙏', desc: '露座の大仏に圧倒される',   landmark: 'kamakura' },
      { id: 'ka_06', name: '江の島',                   emoji: '🏝️', desc: '湘南の海に浮かぶ島' },
      { id: 'ka_07', name: '湘南海岸',                 emoji: '🏄', desc: 'サーファー憧れの海岸' },
      { id: 'ka_08', name: 'ディズニーリゾート',       emoji: '🏰', desc: '夢と魔法の王国' },
      { id: 'ka_09', name: '幕張メッセ',               emoji: '🎪', desc: '巨大イベントの殿堂' },
      { id: 'ka_10', name: '成田国際空港',             emoji: '✈️', desc: '世界への玄関口',           landmark: 'airport' },
      { id: 'ka_11', name: '銚子灯台',                 emoji: '💡', desc: '関東最東端の絶景灯台',     landmark: 'lighthouse' },
      { id: 'ka_12', name: '日光東照宮',               emoji: '⛩️', desc: '見ざる言わざる聞かざる',   landmark: 'nikko' },
      { id: 'ka_13', name: '草津温泉',                 emoji: '♨️', desc: 'ゆもみの伝統が続く名湯',   landmark: 'onsen' },
      { id: 'ka_14', name: '富士山',                   emoji: '🗻', desc: '日本の象徴、世界遺産',     landmark: 'fuji' },
      { id: 'ka_15', name: '箱根',                     emoji: '🏔️', desc: '芦ノ湖越しの富士山' },
      { id: 'ka_16', name: '那須高原',                 emoji: '🐄', desc: '牧場と温泉の高原リゾート' },
      { id: 'ka_17', name: '栃木いちご狩り',           emoji: '🍓', desc: 'とちおとめを摘み放題' },
      { id: 'ka_18', name: '群馬伊香保温泉',           emoji: '♨️', desc: '石段街が情緒たっぷり' },
      { id: 'ka_19', name: '埼玉秩父',                 emoji: '⛰️', desc: '芝桜と秩父夜祭が有名' },
      { id: 'ka_20', name: '茨城袋田の滝',             emoji: '💧', desc: '日本三名瀑のひとつ' },
      { id: 'ka_21', name: '千葉マザー牧場',           emoji: '🐑', desc: '動物とふれあう牧場体験' },
      { id: 'ka_22', name: '横須賀軍港',               emoji: '⚓', desc: '護衛艦が間近で見られる' },
      { id: 'ka_23', name: '三浦半島',                 emoji: '🐟', desc: 'まぐろが名産の半島' },
      { id: 'ka_24', name: '厚木鮎まつり',             emoji: '🐟', desc: '鮎の塩焼きが絶品' },
      { id: 'ka_25', name: '伊豆大島',                 emoji: '🌋', desc: '三原山と椿の島' },
      { id: 'ka_26', name: '熱海温泉',                 emoji: '♨️', desc: '首都圏に近い温泉リゾート' },
      { id: 'ka_27', name: '修善寺',                   emoji: '🌿', desc: '竹林と温泉の伊豆の隠れ里' },
      { id: 'ka_28', name: '富士急ハイランド',         emoji: '🎢', desc: '絶叫マシンが日本一' },
      { id: 'ka_29', name: '河口湖',                   emoji: '🌊', desc: '逆さ富士が映える湖面' },
      { id: 'ka_30', name: '精進湖',                   emoji: '🌅', desc: '富士五湖の中で最も静寂' },
      { id: 'ka_31', name: '軽井沢',                   emoji: '🌲', desc: '避暑地として人気の高原' },
      { id: 'ka_32', name: 'つくば研究学園都市',       emoji: '🚄', desc: '宇宙開発機関も集まる街' },
      { id: 'ka_33', name: '水戸偕楽園',               emoji: '🌸', desc: '梅の名所として全国有名' },
      { id: 'ka_34', name: '鹿島神宮',                 emoji: '⛩️', desc: '武神を祀る格式高い神社' },
      { id: 'ka_35', name: '霞ヶ浦',                   emoji: '🚣', desc: '琵琶湖に次ぐ大きさの湖' },
      { id: 'ka_36', name: '大洗磯前神社',             emoji: '🌊', desc: '岩礁に建つ海の神社' },
      { id: 'ka_37', name: '益子焼の里',               emoji: '🏺', desc: '陶芸の里で器を探す' },
      { id: 'ka_38', name: 'さきたま古墳群',           emoji: '⛰️', desc: '古代の権力者が眠る丘' },
      { id: 'ka_39', name: '川越氷川神社',             emoji: '⛩️', desc: '縁結びで人気の神社' },
      { id: 'ka_40', name: '所沢航空記念公園',         emoji: '✈️', desc: '日本の航空発祥の地' },
      { id: 'ka_41', name: '高尾山',                   emoji: '🏔️', desc: '世界一登山者が多い山' },
      { id: 'ka_42', name: '奥多摩',                   emoji: '🌲', desc: '東京都内の大自然' },
      { id: 'ka_43', name: '青梅昭和の街',             emoji: '🎬', desc: 'レトロな昭和映画看板の街' },
      { id: 'ka_44', name: '八王子城址',               emoji: '🏯', desc: '山城の遺構が残る史跡' },
      { id: 'ka_45', name: '相模湖',                   emoji: '🚣', desc: 'ボート遊びと紅葉が名物' },
      { id: 'ka_46', name: '大山阿夫利神社',           emoji: '⛩️', desc: '大山詣の伝統が続く' },
      { id: 'ka_47', name: '丹沢山',                   emoji: '🦌', desc: '豊かな生態系の登山コース' },
      { id: 'ka_48', name: '江ノ電',                   emoji: '🚃', desc: '海と共に走る路面電車' },
      { id: 'ka_49', name: '平塚七夕まつり',           emoji: '🎋', desc: '七夕飾りが通りを埋め尽くす' },
      { id: 'ka_50', name: '真鶴岬',                   emoji: '🌊', desc: '伊豆半島の付け根の絶景岬' },
      { id: 'ka_51', name: '伊豆シャボテン公園',       emoji: '🌵', desc: 'カピバラの温泉が人気' },
      { id: 'ka_52', name: '下田ペリー来航の地',       emoji: '⚓', desc: '幕末の歴史が刻まれる港' },
      { id: 'ka_53', name: '山中湖',                   emoji: '🌊', desc: '富士五湖最大の高原湖' },
      { id: 'ka_54', name: '御岳山',                   emoji: '🐺', desc: 'オオカミを祀る山岳信仰' },
      { id: 'ka_55', name: '宝登山ろう梅園',           emoji: '🌼', desc: '秩父の冬を彩る黄色い花' },
    ],
  },

  {
    id: 'east_japan',
    defaultLandmark: 'castle',
    name: '東日本',
    emoji: '🏔️',
    phase: 'japan',
    requiredVehicle: 'car',
    baseMoney: 250000,
    baseFollowers: 5000,
    basePop: 300,
    spots: [
      { id: 'ej_01', name: '松島',                 emoji: '🏝️', desc: '日本三景の海と島々' },
      { id: 'ej_02', name: '仙台牛タン',           emoji: '🥩', desc: '炭火で焼く分厚い一枚' },
      { id: 'ej_03', name: '青森ねぶた祭',         emoji: '🏮', desc: '巨大灯篭が夜を照らす' },
      { id: 'ej_04', name: '函館夜景',             emoji: '🌃', desc: '世界三大夜景のひとつ' },
      { id: 'ej_05', name: '十和田湖',             emoji: '🌊', desc: '神秘的な青さの火口湖' },
      { id: 'ej_06', name: '蔵王温泉',             emoji: '♨️', desc: '樹氷と硫黄の絶景温泉' },
      { id: 'ej_07', name: '花巻温泉',             emoji: '♨️', desc: '宮沢賢治の故郷の温泉' },
      { id: 'ej_08', name: '遠野カッパ淵',         emoji: '🟢', desc: 'カッパが棲むという伝説の淵' },
      { id: 'ej_09', name: '秋田なまはげ',         emoji: '👹', desc: '恐怖と感謝の伝統行事' },
      { id: 'ej_10', name: '山形芋煮会',           emoji: '🥣', desc: '河原で鍋を囲む秋の風物詩' },
      { id: 'ej_11', name: '福島の桃',             emoji: '🍑', desc: '日本一の桃の産地' },
      { id: 'ej_12', name: '会津若松城',           emoji: '🏯', desc: '鶴ヶ城と呼ばれる白亜の城', landmark: 'castle' },
      { id: 'ej_13', name: '甲府ぶどう',           emoji: '🍇', desc: '山梨が誇るワインの里' },
      { id: 'ej_14', name: '長野善光寺',           emoji: '⛩️', desc: '7年に一度の御開帳が壮観', landmark: 'jinja' },
      { id: 'ej_15', name: '白馬スキー場',         emoji: '⛷️', desc: 'パウダースノーに世界が驚く', landmark: 'mountain' },
      { id: 'ej_16', name: '弘前城の桜',           emoji: '🌸', desc: '花びらが堀を埋め尽くす' },
      { id: 'ej_17', name: '秋田竿灯まつり',       emoji: '🏮', desc: '巨大な灯籠を体で操る' },
      { id: 'ej_18', name: '山形上山温泉',         emoji: '♨️', desc: '城下町に湧く歴史の湯' },
      { id: 'ej_19', name: '岩手平泉',             emoji: '🛕', desc: '黄金文化が花開いた世界遺産' },
      { id: 'ej_20', name: '盛岡冷麺',             emoji: '🍜', desc: '韓国由来の半透明な麺' },
      { id: 'ej_21', name: '八甲田山',             emoji: '🏔️', desc: '雪の絶景と温泉の名峰' },
      { id: 'ej_22', name: '奥入瀬渓流',           emoji: '💧', desc: '苔と滝が織りなす清流' },
      { id: 'ej_23', name: '男鹿半島',             emoji: '🌊', desc: 'なまはげの故郷の荒磯' },
      { id: 'ej_24', name: '酒田の山居倉庫',       emoji: '🏚️', desc: '米どころ庄内の歴史倉庫' },
      { id: 'ej_25', name: '山寺立石寺',           emoji: '⛩️', desc: '1015段の石段を登る' },
      { id: 'ej_26', name: '猪苗代湖',             emoji: '🌊', desc: '野口英世の故郷に輝く湖' },
      { id: 'ej_27', name: '那須岳',               emoji: '🌋', desc: '活火山の噴煙が迫力満点' },
      { id: 'ej_28', name: '日光いろは坂',         emoji: '🍁', desc: '紅葉シーズンの大渋滞名所' },
      { id: 'ej_29', name: '尾瀬ヶ原',             emoji: '🌿', desc: '水芭蕉の湿原を歩く' },
      { id: 'ej_30', name: '妙高高原',             emoji: '⛷️', desc: 'スキーリゾートの名所' },
      { id: 'ej_31', name: '松本城',               emoji: '🏯', desc: '国宝の黒い天守が美しい' },
      { id: 'ej_32', name: '上高地',               emoji: '🏔️', desc: '日本アルプスの絶景別天地' },
      { id: 'ej_33', name: '安曇野わさび農場',     emoji: '🌿', desc: '清流で育てるわさびの産地' },
      { id: 'ej_34', name: '諏訪湖',               emoji: '🌊', desc: '御神渡りが出現する不思議な湖' },
      { id: 'ej_35', name: '高遠の桜',             emoji: '🌸', desc: '天下第一の桜と称えられる' },
      { id: 'ej_36', name: '塩原温泉',             emoji: '♨️', desc: '那須連山の麓の渓谷温泉' },
      { id: 'ej_37', name: '新潟佐渡島',           emoji: '🏝️', desc: '日本最大の離島の金山' },
      { id: 'ej_38', name: '越後湯沢温泉',         emoji: '♨️', desc: 'スキーと地酒の雪国' },
      { id: 'ej_39', name: '富山黒部ダム',         emoji: '💧', desc: '戦後最大の難工事の証' },
      { id: 'ej_40', name: '白川郷合掌造り',       emoji: '🏠', desc: '雪景色に映える世界遺産' },
      { id: 'ej_41', name: '五箇山',               emoji: '🏠', desc: '秘境に残る合掌集落' },
      { id: 'ej_42', name: '立山黒部アルペンルート', emoji: '🏔️', desc: '雪の大谷壁が圧倒的' },
      { id: 'ej_43', name: '金沢兼六園',           emoji: '🌳', desc: '日本三名園の雪吊り' },
      { id: 'ej_44', name: '金沢ひがし茶屋街',     emoji: '🏮', desc: '格子窓の芸妓文化が残る' },
      { id: 'ej_45', name: '輪島朝市',             emoji: '🦀', desc: '能登の海の幸が集まる市' },
      { id: 'ej_46', name: '永平寺',               emoji: '⛩️', desc: '曹洞宗の厳格な修行道場' },
      { id: 'ej_47', name: '東尋坊',               emoji: '🌊', desc: '荒波が打ち寄せる断崖絶壁' },
      { id: 'ej_48', name: '山代温泉',             emoji: '♨️', desc: '加賀温泉郷の総湯文化' },
      { id: 'ej_49', name: '三方五湖',             emoji: '🌊', desc: '五色に輝く五つの湖' },
      { id: 'ej_50', name: '気仙沼の海鮮',         emoji: '🦞', desc: '三陸の豊かな海の幸' },
    ],
  },

  {
    id: 'japan',
    defaultLandmark: 'kyoto_fushimi',
    name: '全国',
    emoji: '🗾',
    phase: 'japan',
    requiredVehicle: 'airplane',
    baseMoney: 1500000,
    baseFollowers: 30000,
    basePop: 1500,
    spots: [
      { id: 'jp_01', name: '京都伏見稲荷',         emoji: '⛩️', desc: '千本鳥居が延々と続く',     landmark: 'kyoto_fushimi' },
      { id: 'jp_02', name: '京都金閣寺',           emoji: '🥇', desc: '黄金に輝く舎利殿',         landmark: 'kyoto_kinkakuji' },
      { id: 'jp_03', name: '京都嵐山',             emoji: '🎋', desc: '竹林と大堰川の絶景',       landmark: 'kyoto_arashiyama' },
      { id: 'jp_04', name: '大阪道頓堀',           emoji: '🦀', desc: 'グリコ看板とたこ焼き',     landmark: 'osaka_dotonbori' },
      { id: 'jp_05', name: '奈良の鹿',             emoji: '🦌', desc: 'せんべいを奪う野生の鹿',   landmark: 'deer' },
      { id: 'jp_06', name: '広島原爆ドーム',       emoji: '🕊️', desc: '平和への誓いが刻まれる' },
      { id: 'jp_07', name: '宮島厳島神社',         emoji: '⛩️', desc: '海に浮かぶ朱色の大鳥居', landmark: 'ise' },
      { id: 'jp_08', name: '高知よさこい祭',       emoji: '💃', desc: '鳴子の音と踊りの熱狂' },
      { id: 'jp_09', name: '愛媛道後温泉',         emoji: '♨️', desc: '日本最古の温泉が今も現役' },
      { id: 'jp_10', name: '博多屋台',             emoji: '🍜', desc: 'ラーメン文化の本場',       landmark: 'ramen' },
      { id: 'jp_11', name: '長崎ハウステンボス',   emoji: '🌷', desc: 'オランダの街並みが広がる' },
      { id: 'jp_12', name: '熊本城',               emoji: '🏯', desc: '加藤清正が築いた名城',     landmark: 'castle' },
      { id: 'jp_13', name: '阿蘇山',               emoji: '🌋', desc: '世界最大のカルデラ地形',   landmark: 'kyushu_aso' },
      { id: 'jp_14', name: '指宿砂風呂',           emoji: '🏖️', desc: '砂に埋まって温まる' },
      { id: 'jp_15', name: '沖縄美ら海水族館',     emoji: '🐋', desc: 'ジンベエザメが泳ぐ大水槽', landmark: 'aquarium' },
      { id: 'jp_16', name: '那覇国際通り',         emoji: '🏬', desc: '沖縄文化と土産が集まる' },
      { id: 'jp_17', name: '石垣島',               emoji: '🏝️', desc: '珊瑚礁と透明度抜群の海',   landmark: 'tropical_beach' },
      { id: 'jp_18', name: '北海道札幌',           emoji: '🍦', desc: '雪まつりと時計台の街',     landmark: 'hokkaido_sapporo' },
      { id: 'jp_19', name: '函館朝市',             emoji: '🦑', desc: 'イカ刺しが朝から食べられる' },
      { id: 'jp_20', name: '富良野ラベンダー',     emoji: '💜', desc: '紫の絨毯が一面に広がる',   landmark: 'hokkaido_furano' },
      { id: 'jp_21', name: '知床',                 emoji: '🐻', desc: '手つかずの自然が残る世界遺産' },
      { id: 'jp_22', name: '京都嵯峨野トロッコ',   emoji: '🚂', desc: 'トロッコ列車で渓谷を行く' },
      { id: 'jp_23', name: '京都祇園',             emoji: '👘', desc: '舞妓さんに出会える路地' },
      { id: 'jp_24', name: '奈良東大寺',           emoji: '🛕', desc: '世界最大の木造建築' },
      { id: 'jp_25', name: '大阪城',               emoji: '🏯', desc: '豊臣秀吉が築いた巨城' },
      { id: 'jp_26', name: '神戸北野異人館',       emoji: '🏠', desc: '風見鶏の館が有名' },
      { id: 'jp_27', name: '姫路城',               emoji: '🏯', desc: '白鷺城と呼ばれる国宝' },
      { id: 'jp_28', name: '鳥取砂丘',             emoji: '🏜️', desc: '日本唯一の大砂丘' },
      { id: 'jp_29', name: '出雲大社',             emoji: '⛩️', desc: '縁結びの神様を参拝' },
      { id: 'jp_30', name: '角島大橋',             emoji: '🌊', desc: '山口の絶景エメラルドの海' },
      { id: 'jp_31', name: '秋芳洞',               emoji: '🪨', desc: '日本最大の鍾乳洞' },
      { id: 'jp_32', name: '萩の城下町',           emoji: '🏘️', desc: '明治維新志士ゆかりの地' },
      { id: 'jp_33', name: '徳島阿波踊り',         emoji: '💃', desc: '踊る阿呆に見る阿呆' },
      { id: 'jp_34', name: '香川うどんの里',       emoji: '🍜', desc: '讃岐うどんを巡礼する' },
      { id: 'jp_35', name: '高松栗林公園',         emoji: '🌳', desc: '特別名勝の大名庭園' },
      { id: 'jp_36', name: '松山城',               emoji: '🏯', desc: '山の頂に立つ現存天守' },
      { id: 'jp_37', name: '大分別府温泉',         emoji: '♨️', desc: '地獄めぐりが人気の温泉地' },
      { id: 'jp_38', name: '宮崎高千穂峡',         emoji: '💧', desc: '神々が住んだという渓谷' },
      { id: 'jp_39', name: '屋久島縄文杉',         emoji: '🌲', desc: '樹齢3000年を超える巨木' },
      { id: 'jp_40', name: '種子島宇宙センター',   emoji: '🚀', desc: 'ロケット打ち上げの一大拠点' },
      { id: 'jp_41', name: '与那国島',             emoji: '🏝️', desc: '日本最西端の孤島' },
      { id: 'jp_42', name: '宮古島',               emoji: '🌊', desc: '世界屈指の透明度の海' },
      { id: 'jp_43', name: '首里城',               emoji: '🏯', desc: '琉球王国の栄華を伝える' },
      { id: 'jp_44', name: '大阪USJ',             emoji: '🎢', desc: '魔法の世界に大興奮' },
      { id: 'jp_45', name: '福岡太宰府天満宮',     emoji: '⛩️', desc: '梅と学問の神様' },
      { id: 'jp_46', name: '長崎軍艦島',           emoji: '🏚️', desc: '廃墟の島が世界遺産に' },
      { id: 'jp_47', name: '佐賀伊万里焼',         emoji: '🏺', desc: '色絵磁器の繊細な美しさ' },
      { id: 'jp_48', name: '大分日田温泉',         emoji: '♨️', desc: '大分の秘湯でゆっくり湯治' },
      { id: 'jp_49', name: '洞爺湖',               emoji: '🌊', desc: '北海道の大カルデラ湖' },
      { id: 'jp_50', name: '網走流氷',             emoji: '🧊', desc: '流氷砕氷船で真冬の海へ' },
      { id: 'jp_51', name: '小樽運河',             emoji: '🚣', desc: 'レンガ倉庫と石畳の港町' },
      { id: 'jp_52', name: '旭川旭山動物園',       emoji: '🐧', desc: 'ペンギンの行進が有名' },
      { id: 'jp_53', name: '釧路湿原',             emoji: '🌿', desc: '日本最大の湿原を丹頂が舞う' },
      { id: 'jp_54', name: '摩周湖',               emoji: '🌊', desc: '霧の湖と呼ばれる神秘の湖' },
      { id: 'jp_55', name: '礼文島',               emoji: '🌸', desc: '花の浮島に高山植物が咲く' },
    ],
  },

  {
    id: 'world',
    defaultLandmark: 'paris',
    name: '海外',
    emoji: '🌍',
    phase: 'europe',
    requiredVehicle: 'world_ticket',
    baseMoney: 10000000,
    baseFollowers: 200000,
    basePop: 10000,
    spots: [
      // Europe
      { id: 'wo_01', name: 'パリ エッフェル塔',       emoji: '🗼', desc: '鉄の貴婦人が夜に輝く',   landmark: 'paris',       phase: 'europe' },
      { id: 'wo_02', name: 'ロンドン ビッグベン',     emoji: '🕰️', desc: '英国の象徴が鐘を鳴らす', landmark: 'london',      phase: 'europe' },
      { id: 'wo_03', name: 'ローマ コロッセウム',     emoji: '🏛️', desc: '剣闘士の戦いの舞台',     landmark: 'rome',        phase: 'europe' },
      { id: 'wo_04', name: 'バルセロナ サグラダ',     emoji: '⛪', desc: 'ガウディの未完の大聖堂', landmark: 'sagrada',     phase: 'europe' },
      { id: 'wo_05', name: 'アムステルダム',           emoji: '🌷', desc: '風車とチューリップの国', landmark: 'windmill',    phase: 'europe' },
      { id: 'wo_06', name: 'サントリーニ島',           emoji: '🏛️', desc: '白と青のエーゲ海の楽園', landmark: 'santorini',   phase: 'europe' },
      { id: 'wo_07', name: 'プラハ旧市街',             emoji: '🏰', desc: '百塔の街の石畳を歩く',   phase: 'europe' },
      { id: 'wo_08', name: 'ウィーン音楽の都',         emoji: '🎻', desc: 'モーツァルトが息づく街', phase: 'europe' },
      { id: 'wo_09', name: 'スイス アルプス',          emoji: '🏔️', desc: '少女ハイジの山が目の前に', phase: 'europe' },
      { id: 'wo_10', name: 'ヴェネツィア',             emoji: '🚣', desc: 'ゴンドラで水路を行く',   phase: 'europe' },
      { id: 'wo_11', name: 'フィレンツェ',             emoji: '🎨', desc: 'ルネサンス芸術の宝庫',   phase: 'europe' },
      { id: 'wo_12', name: 'マドリード',               emoji: '💃', desc: 'フラメンコが夜を彩る',   phase: 'europe' },
      { id: 'wo_13', name: 'リスボン路面電車',         emoji: '🚃', desc: '坂の街を電車が上る',     phase: 'europe' },
      { id: 'wo_14', name: 'ブダペスト夜景',           emoji: '🌃', desc: 'ドナウの真珠と呼ばれる', phase: 'europe' },
      { id: 'wo_15', name: 'アイスランド オーロラ',   emoji: '🌌', desc: '天空を彩る光のカーテン', phase: 'europe' },
      // Americas
      { id: 'wo_16', name: 'ニューヨーク',             emoji: '🗽', desc: '自由の女神が迎える街',   landmark: 'ny',          phase: 'americas' },
      { id: 'wo_17', name: 'ラスベガス',               emoji: '🎰', desc: '砂漠に輝くカジノの街',   landmark: 'vegas',       phase: 'americas' },
      { id: 'wo_18', name: 'ハリウッド',               emoji: '🎬', desc: '映画産業の聖地',         landmark: 'hollywood',   phase: 'americas' },
      { id: 'wo_19', name: 'マチュピチュ',             emoji: '🏔️', desc: '空中都市の神秘に触れる', landmark: 'machupichu',  phase: 'americas' },
      { id: 'wo_20', name: 'リオデジャネイロ',         emoji: '🎭', desc: 'カーニバルと巨大キリスト像', landmark: 'rio',      phase: 'americas' },
      { id: 'wo_21', name: 'グランドキャニオン',       emoji: '🏜️', desc: '大地の裂け目の絶景',     phase: 'americas' },
      { id: 'wo_22', name: 'ナイアガラの滝',           emoji: '💧', desc: '轟音と水しぶきの大瀑布', phase: 'americas' },
      { id: 'wo_23', name: 'メキシコ テオティワカン', emoji: '🔺', desc: '太陽と月のピラミッド',   phase: 'americas' },
      { id: 'wo_24', name: 'カナダ バンフ',            emoji: '🏔️', desc: 'エメラルドの湖と氷河',   phase: 'americas' },
      { id: 'wo_25', name: 'ハワイ ワイキキビーチ',   emoji: '🌺', desc: 'ダイヤモンドヘッドが絵になる', phase: 'americas' },
      // Middle East & Africa
      { id: 'wo_26', name: 'ドバイ ブルジュハリファ', emoji: '🏙️', desc: '世界一の高さを誇る摩天楼', landmark: 'burj',       phase: 'middleeast' },
      { id: 'wo_27', name: 'カイロ ピラミッド',       emoji: '🔺', desc: '古代七不思議の唯一の現存', landmark: 'pyramids',   phase: 'middleeast' },
      { id: 'wo_28', name: 'イスタンブール',           emoji: '🕌', desc: 'アジアとヨーロッパの交差点', phase: 'middleeast' },
      { id: 'wo_29', name: 'モロッコ マラケシュ',     emoji: '🏺', desc: '迷宮スークで感覚を磨く', phase: 'middleeast' },
      { id: 'wo_30', name: 'ヨルダン ペトラ遺跡',     emoji: '🏛️', desc: '岩を刻んだ薔薇色の古代都市', phase: 'middleeast' },
      { id: 'wo_31', name: 'ケニア サファリ',         emoji: '🦁', desc: '野生の王者がすぐそこに', phase: 'middleeast' },
      { id: 'wo_32', name: 'タンザニア キリマンジャロ', emoji: '🏔️', desc: 'アフリカ最高峰に挑む',   phase: 'middleeast' },
      // Asia
      { id: 'wo_33', name: 'タージ・マハル',           emoji: '🕌', desc: '愛の白大理石の廟',       landmark: 'taj_mahal',   phase: 'asia' },
      { id: 'wo_34', name: 'シンガポール',             emoji: '🦁', desc: 'マーライオンと未来都市', landmark: 'merlion',     phase: 'asia' },
      { id: 'wo_35', name: 'バリ棚田',                 emoji: '🌾', desc: '緑の段々畑が広がる',     landmark: 'rice_terraces', phase: 'asia' },
      { id: 'wo_36', name: 'ソウル景福宮',             emoji: '🏯', desc: '朝鮮王朝の宮殿と韓服体験', landmark: 'korean_palace', phase: 'asia' },
      { id: 'wo_37', name: '万里の長城',               emoji: '🧱', desc: '宇宙から見える人類の遺産', landmark: 'great_wall', phase: 'asia' },
      { id: 'wo_38', name: 'バンコク 王宮',            emoji: '🛕', desc: '黄金に輝く寺院が並ぶ',   phase: 'asia' },
      { id: 'wo_39', name: 'ハノイ ハロン湾',          emoji: '🏝️', desc: '海に浮かぶ奇岩の絶景',   phase: 'asia' },
      { id: 'wo_40', name: 'アンコールワット',         emoji: '🛕', desc: 'クメール帝国の石造神殿', phase: 'asia' },
      { id: 'wo_41', name: '北京 故宮',               emoji: '🏯', desc: '紫禁城の圧倒的スケール', phase: 'asia' },
      { id: 'wo_42', name: '上海 外灘',               emoji: '🌃', desc: '黄浦江沿いの近代建築群', phase: 'asia' },
      { id: 'wo_43', name: '香港 夜景',               emoji: '🌃', desc: '百万ドルの夜景が広がる', phase: 'asia' },
      { id: 'wo_44', name: '台湾 九份',               emoji: '🏮', desc: '赤提灯が灯る山の街',     phase: 'asia' },
      { id: 'wo_45', name: 'ネパール エベレスト',     emoji: '🏔️', desc: '世界最高峰を望む絶景',   phase: 'asia' },
      { id: 'wo_46', name: 'モルディブ',               emoji: '🏝️', desc: '透き通るインド洋の楽園', phase: 'asia' },
      { id: 'wo_47', name: 'スリランカ 仏歯寺',       emoji: '🛕', desc: 'ブッダの歯を祀る聖地',   phase: 'asia' },
      { id: 'wo_48', name: 'ミャンマー バガン',       emoji: '🛕', desc: '平原に続く無数の仏塔群', phase: 'asia' },
      { id: 'wo_49', name: 'オーストラリア ウルル',   emoji: '🪨', desc: '赤い巨岩に沈む夕日',     phase: 'europe' },
      { id: 'wo_50', name: 'ガラパゴス諸島',           emoji: '🦎', desc: 'イグアナと共存する進化の島', phase: 'americas' },
    ],
  },

  {
    id: 'space',
    defaultLandmark: 'rocket_launch',
    name: '宇宙',
    emoji: '🚀',
    phase: 'space',
    requiredVehicle: 'rocket',
    baseMoney: 100000000000,
    baseFollowers: 10000000,
    basePop: 1000000,
    spots: [
      { id: 'sp_01', name: '国際宇宙ステーション', emoji: '🛸', desc: '地球を90分で一周する' },
      { id: 'sp_02', name: '月面 静かの海',       emoji: '🌕', desc: 'アポロが降り立った場所' },
      { id: 'sp_03', name: '月面 クレーター',     emoji: '🌑', desc: '隕石が刻んだ無数の傷跡' },
      { id: 'sp_04', name: '月面 裏側',           emoji: '🌚', desc: '地球から見えない謎の面' },
      { id: 'sp_05', name: '火星 オリンポス山',   emoji: '🌋', desc: '太陽系最大の火山' },
      { id: 'sp_06', name: '火星 マリネリス峡谷', emoji: '🏜️', desc: 'グランドキャニオンの10倍' },
      { id: 'sp_07', name: '火星 極冠',           emoji: '❄️', desc: '二酸化炭素の氷が広がる' },
      { id: 'sp_08', name: '木星の輝き',           emoji: '🪐', desc: '大赤斑が渦巻く巨大嵐' },
      { id: 'sp_09', name: '土星の輪',             emoji: '🪐', desc: '無数の氷粒が描くリング' },
      { id: 'sp_10', name: '土星 タイタン',       emoji: '🌫️', desc: '液体メタンの湖が存在' },
      { id: 'sp_11', name: '天王星の極',           emoji: '💙', desc: '横倒しで自転する青い惑星' },
      { id: 'sp_12', name: '海王星',               emoji: '💙', desc: '太陽系最強の風が吹く' },
      { id: 'sp_13', name: 'アステロイドベルト',   emoji: '🪨', desc: '無数の岩石が漂う宇宙の帯' },
      { id: 'sp_14', name: '木星 エウロパ',       emoji: '🧊', desc: '氷の下に海が広がるかも' },
      { id: 'sp_15', name: '木星 イオ',           emoji: '🌋', desc: '最も活発な火山活動' },
      { id: 'sp_16', name: '彗星追跡',             emoji: '☄️', desc: '氷と塵の尾が輝く天体' },
      { id: 'sp_17', name: 'オールトの雲',         emoji: '✨', desc: '太陽系の果ての氷天体群' },
      { id: 'sp_18', name: 'ラグランジュポイント', emoji: '🔭', desc: '重力の谷間の安定点' },
      { id: 'sp_19', name: '太陽 コロナ観測',     emoji: '☀️', desc: '100万度の大気が踊る' },
      { id: 'sp_20', name: '水星 クレーター地形', emoji: '⚫', desc: '昼夜の温度差が700度' },
      { id: 'sp_21', name: '金星 硫酸の雲',       emoji: '🟡', desc: '460度の地獄の惑星' },
      { id: 'sp_22', name: '火星基地',             emoji: '🏗️', desc: '人類初の惑星間居住施設' },
      { id: 'sp_23', name: '深宇宙ゲートウェイ',   emoji: '🛸', desc: '月軌道の次世代宇宙基地' },
      { id: 'sp_24', name: 'ブラックホール近傍',   emoji: '⚫', desc: '時空が歪む特異点の縁' },
      { id: 'sp_25', name: 'パルサー',             emoji: '💫', desc: '秒単位で点滅する中性子星' },
      { id: 'sp_26', name: '星雲の中',             emoji: '🌌', desc: '新しい星が生まれる産声の場' },
      { id: 'sp_27', name: '銀河系中心',           emoji: '🌌', desc: '超巨大ブラックホールが潜む' },
      { id: 'sp_28', name: 'アンドロメダ銀河',     emoji: '🌀', desc: '250万光年先の隣人銀河' },
      { id: 'sp_29', name: '宇宙の果て',           emoji: '∞',  desc: '観測可能な宇宙の限界へ' },
      { id: 'sp_30', name: '並行宇宙の入口',       emoji: '🌀', desc: '多元宇宙論の向こう側へ' },
    ],
  },
];

// ============================================================
// VEHICLES
// ============================================================
const VEHICLES = [
  {
    id: 'bicycle',
    name: '自転車',
    emoji: '🚲',
    sprite: 'bicycle',
    description: '足で漕いで市内へ！エリアが広がる',
    autoSpeed: 0.08,
    clickBonus: 0.05,
    baseCost: 5000,
    unlocksArea: 'city',
    unlockCondition: { areaId: 'neighborhood', spotsNeeded: 20 },
  },
  {
    id: 'ekickboard',
    name: '電動キックボード',
    emoji: '🛴',
    sprite: 'ekickboard',
    description: '都内を颯爽と巡る。山手線エリア解放！',
    autoSpeed: 0.20,
    clickBonus: 0.05,
    baseCost: 30000,
    unlocksArea: 'downtown',
    unlockCondition: { areaId: 'city', spotsNeeded: 20 },
  },
  {
    id: 'moped',
    name: '原付き',
    emoji: '🛵',
    sprite: 'moped',
    description: '関東圏を駆け回る！スポット数爆増',
    autoSpeed: 0.40,
    clickBonus: 0.08,
    baseCost: 150000,
    unlocksArea: 'kanto',
    unlockCondition: { areaId: 'downtown', spotsNeeded: 20 },
  },
  {
    id: 'car',
    name: '車',
    emoji: '🚗',
    sprite: 'car',
    description: '東日本を自由に旅する。高速道路も走れる',
    autoSpeed: 0.70,
    clickBonus: 0.08,
    baseCost: 900000,
    unlocksArea: 'east_japan',
    unlockCondition: { areaId: 'kanto', spotsNeeded: 20 },
  },
  {
    id: 'airplane',
    name: '飛行機',
    emoji: '✈️',
    sprite: 'airplane',
    description: '全国を飛び回る！日本全土が舞台に',
    autoSpeed: 1.5,
    clickBonus: 0.10,
    baseCost: 5000000,
    unlocksArea: 'japan',
    unlockCondition: { areaId: 'east_japan', spotsNeeded: 20 },
  },
  {
    id: 'world_ticket',
    name: '世界一周チケット',
    emoji: '🌍',
    sprite: 'airplane',
    description: '海外へ！世界中の絶景を収める',
    autoSpeed: 2.5,
    clickBonus: 0.10,
    baseCost: 50000000,
    unlocksArea: 'world',
    unlockCondition: { areaId: 'japan', spotsNeeded: 20 },
  },
  {
    id: 'rocket',
    name: 'ロケット',
    emoji: '🚀',
    sprite: 'rocket',
    description: '宇宙へ！人類代表インフルエンサー誕生',
    autoSpeed: 4.0,
    clickBonus: 0.15,
    baseCost: 50000000000,
    unlocksArea: 'space',
    unlockCondition: { areaId: 'world', spotsNeeded: 20 },
  },
];

const VEHICLE_COST_MULT = 1.15;  // 乗り物Lv.N→N+1 のコスト倍率
const SPONSOR_COST_MULT = 1.15;  // スポンサー N件目のコスト倍率

// ============================================================
// SPONSORS
// ============================================================
const SPONSORS = [
  {
    id: 'affiliate',
    name: 'アフィリエイト',
    emoji: '🔗',
    description: 'ブログやSNSで商品を紹介する',
    baseIncome: 100,
    followerCost: 30,
    popularityRequired: 0,
  },
  {
    id: 'youtube',
    name: 'YouTube広告',
    emoji: '▶️',
    description: '動画再生数に応じて収益が入る',
    baseIncome: 600,
    followerCost: 120,
    popularityRequired: 5,
  },
  {
    id: 'travel_gear',
    name: 'トラベルギア',
    emoji: '🎒',
    description: '旅行用品メーカーの案件',
    baseIncome: 4000,
    followerCost: 350,
    popularityRequired: 15,
  },
  {
    id: 'tourist_spot',
    name: '観光地PR',
    emoji: '🗺️',
    description: '地方自治体の観光PR案件',
    baseIncome: 30000,
    followerCost: 1500,
    popularityRequired: 50,
  },
  {
    id: 'hotel_chain',
    name: 'ホテルチェーン',
    emoji: '🏨',
    description: '大手ホテルのタイアップ宿泊',
    baseIncome: 200000,
    followerCost: 6000,
    popularityRequired: 200,
  },
  {
    id: 'airline',
    name: '航空会社',
    emoji: '✈️',
    description: '航空会社の公式アンバサダー',
    baseIncome: 1500000,
    followerCost: 25000,
    popularityRequired: 800,
  },
  {
    id: 'tourism_ministry',
    name: '観光庁',
    emoji: '🏛️',
    description: '国の観光大使として活動',
    baseIncome: 12000000,
    followerCost: 120000,
    popularityRequired: 4000,
  },
  {
    id: 'space_agency',
    name: '宇宙機関',
    emoji: '🚀',
    description: '宇宙開発機関の広報担当',
    baseIncome: 100000000,
    followerCost: 800000,
    popularityRequired: 20000,
  },
  {
    id: 'galactic_corp',
    name: '銀河コーポレーション',
    emoji: '🌌',
    description: '宇宙間企業のスーパーアンバサダー',
    baseIncome: 800000000,
    followerCost: 8000000,
    popularityRequired: 300000,
  },
];

// ============================================================
// EQUIPMENT
// ============================================================
const EQUIPMENT = [
  { id: 'ring_light',  name: 'リングライト',      emoji: '💡', description: '顔まわりの照明をプロ仕様に。映え度UP',          baseMult: 1.2, baseCost: 3000,       costMult: 1.2, popularityRequired: 0     },
  { id: 'smartphone',  name: 'スマホ（最新機種）', emoji: '📱', description: '最新カメラで撮影クオリティが大幅UP',             baseMult: 1.3, baseCost: 15000,      costMult: 1.25,popularityRequired: 0     },
  { id: 'mic',         name: 'マイク',             emoji: '🎤', description: 'クリアな音声でエンゲージメントUP',              baseMult: 1.25,baseCost: 20000,      costMult: 1.2, popularityRequired: 5     },
  { id: 'gimbal',      name: 'ジンバル',           emoji: '🎥', description: 'なめらかな動画でプロ感が出る',                  baseMult: 1.3, baseCost: 50000,      costMult: 1.2, popularityRequired: 15    },
  { id: 'dslr',        name: '一眼レフ',           emoji: '📷', description: 'ボケ感のある写真でいいね急増',                  baseMult: 1.5, baseCost: 200000,     costMult: 1.3, popularityRequired: 25    },
  { id: 'drone',       name: 'ドローン',           emoji: '🚁', description: '空撮で唯一無二の構図。再生数爆増',              baseMult: 2.0, baseCost: 800000,     costMult: 1.35,popularityRequired: 60    },
  { id: 'cam360',      name: '360°カメラ',         emoji: '🌐', description: '没入感で視聴継続率が跳ね上がる',                baseMult: 1.8, baseCost: 3000000,    costMult: 1.3, popularityRequired: 200   },
  { id: 'pro_video',   name: 'プロ用ビデオカメラ', emoji: '🎬', description: '映画レベルの映像でスポンサー殺到',              baseMult: 2.5, baseCost: 15000000,   costMult: 1.4, popularityRequired: 1000  },
  { id: 'space_cam',   name: '宇宙望遠鏡カメラ',  emoji: '🔭', description: '宇宙の絶景を超解像で記録',                      baseMult: 4.0, baseCost: 200000000,  costMult: 1.5, popularityRequired: 10000 },
  { id: 'quantum_cam', name: '量子カメラ',         emoji: '⚛️', description: '時空を超えた撮影で宇宙規模バズ',                baseMult: 8.0, baseCost: 5000000000, costMult: 1.6, popularityRequired: 100000},
];
